apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: go-zqivyyrk
  janus-idp.io/tekton: go-zqivyyrk
  backstage.io/kubernetes-id: go-zqivyyrk
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: go-zqivyyrk
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
